apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-debug-assistant.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-debug-assistant.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.appConfig.appName | quote }}
  APP_ENV: {{ .Values.appConfig.appEnv | quote }}
  RUN_DB_MIGRATIONS: {{ .Values.appConfig.runDbMigrations | quote }}
  LOG_LEVEL: {{ .Values.appConfig.logLevel | quote }}
  ALLOW_SQLITE_FALLBACK: {{ .Values.appConfig.allowSqliteFallback | quote }}
  EMBEDDING_PROVIDER: {{ .Values.appConfig.embeddingProvider | quote }}
  LLM_PROVIDER: {{ .Values.appConfig.llmProvider | quote }}
